// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/open-portfolios/review/internal/biz"
	"github.com/open-portfolios/review/internal/conf"
	"github.com/open-portfolios/review/internal/data"
	"github.com/open-portfolios/review/internal/infra"
	"github.com/open-portfolios/review/internal/server"
	"github.com/open-portfolios/review/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, snowflake *conf.Snowflake, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup := data.NewData(db, logger)
	reviewRepo := data.NewReviewRepo(dataData, logger)
	snowflakeRepo, err := infra.NewSnowflakeRepo(snowflake)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	reviewUsecase := biz.NewReviewUsecase(reviewRepo, snowflakeRepo, logger)
	reviewService := service.NewReviewService(reviewUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, reviewService, logger)
	httpServer := server.NewHTTPServer(confServer, reviewService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
